- type: job
  id: NFPirate
  name: job-name-nf-pirate
  description: job-description-nf-pirate
  playTimeTracker: JobPirate
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 86400 # 24 hours
    - !type:DepartmentTimeRequirement
      department: Security
      time: 29800 # 3 hrs
    - !type:RoleTimeRequirement
      role: JobSecurityOfficer
      time: 43200 # 12 hours
  startingGear: NFPirateGear
  alwaysUseSpawner: true
  hideConsoleVisibility: true
  canBeAntag: true
  icon: "JobIconNFPirate"
  supervisors: job-supervisors-nf-pirate
  weight: 20
  displayWeight: 20
  setPreference: true
  newPlayerMessage: false
  access:
  - Pirate
  accessGroups:
  - GeneralAccess
  special:
  - !type:AddComponentSpecial
    components:
    - type: AutoPirate
    - type: SpecialSectorStationRecord # must be given on spawn
      recordGeneration: FalseRecord
    - type: Company
      companyName: None
    - type: DisableSuitSensors
  - !type:AddImplantSpecial
    implants: [ FreelanceTrackingImplant ]
  - !type:GiveItemOnHolidaySpecial # Even pirates get a piece of cake.
    holiday: FrontierBirthday
    prototype: FrontierBirthdayGift

- type: startingGear
  id: NFPirateGear
  equipment:
    belt: ClothingBeltUtility
    pocket1: BasePirateUplinkPirateCrew
  storage:
    back:
    - AppraisalTool

- type: chameleonOutfit
  id: NFPirateChameleonOutfit
  job: NFPirate
