- type: job
  id: Mercenary
  name: job-name-mercenary
  description: job-description-mercenary
  playTimeTracker: JobMercenary
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 108000
  startingGear: MercenaryGear
  canBeAntag: true
  icon: "JobIconMercenary"
  supervisors: job-supervisors-hire
  weight: 3 # Prioritize station & department jobs
  displayWeight: 20 # Second from the bottom
  setPreference: true
  access:
  - Mercenary
  accessGroups:
  - GeneralAccess
  special:
  - !type:GiveItemOnHolidaySpecial
    holiday: FrontierBirthday
    prototype: FrontierBirthdayGift

- type: startingGear
  id: MercenaryGear
#Lua add uplink for limited mercenary
  equipment:
    pocket1: BaseMercenaryUplinkRadioMercenary

- type: chameleonOutfit
  id: MercenaryBaseChameleonOutfit
  job: MercenaryBase
  equipment:
    jumpsuit: ClothingUniformJumpsuitMercenary

# Interview variant
- type: job
  id: MercenaryInterview
  name: job-name-mercenary-interview
  description: job-mercenary-pilot
  playTimeTracker: JobMercenaryInterview
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 108000
  setPreference: false
  startingGear: MercenaryHologramGear
  icon: "JobIconMercenary"
  supervisors: job-supervisors-hire
  access:
  - Mercenary
  accessGroups:
  - GeneralAccess
  jobEntity: InterviewHologramMercenary
  newPlayerMessage: false

- type: startingGear
  id: MercenaryHologramGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitMercenary
    shoes: ClothingShoesBootsMercenary

- type: chameleonOutfit
  id: MercenaryChameleonOutfit
  job: Mercenary
  equipment:
    head: ClothingHeadHelmetMercenary
    eyes: ClothingEyesGlassesCheapSunglasses
    mask: ClothingMaskGasMercenary
    neck: ClothingNeckIFFNeutral
    outerClothing: ClothingOuterVestWebMercenary
    gloves: ClothingHandsGlovesCombat
